### ISSUE TITLE
`unwrap` is a bit uninituitive.

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cli#68]
When doing usability studies, someone did `.execute().unwrap()`, not realizing there was an `.unwrap()` (despite all the docs).

Unfortunately, neither of us came up with better names.

**Comment by porglezomp** [comment]
`.assert()` perhaps?

**Comment by killercup** [comment]
I don't agree that `.unwrap()` is unintuitive.

I think `.unwrap()` is fine: It's what people already know from Option and Result. The docs are good, too, even the Readme shows `.unwrap()`. Hell, I even think `.execute().unwrap()` is fine! It's just not as short as it could be. And if someone listens to my prayers (for an impl of RFC1937), we can just use `.execute()?` everywhere.

`Assert::main_binary().succeeds().assert()` OTOH reads a bit like a stutter. Or, now that I think about it, a prayer. Just with `assert` instead of "Amen".

**Comment by epage** [comment]
I agree that `unwrap` aligns well with std.

> Hell, I even think `.execute().unwrap()`

The one downside is that the output isn't as clean.

Lesson: naming is hard, let's go shopping.

**Comment by epage** [comment]
So thinking more about this.
- `unwrap` makes sense in the context of Rust
- `execute` has some alternatives
  - `ok` could make sense, see [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or)
  - `status` could make sense, see [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html#method.status)
  - `wait` could make sense, see [`Child`](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait)

**Comment by epage** [comment]
I think its decided to keep `unwrap` as-is.
